# Generated by Django 3.1.3 on 2021-03-22 12:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='testLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=home.models.uniqueKeyGenerator, max_length=70, unique=True, verbose_name='Уникальный ключ')),
                ('title', models.CharField(default='Подробнее', max_length=120, verbose_name='Текст кнопки')),
                ('openTime', models.IntegerField(default=1, help_text='при 0 открывается сразу', verbose_name='Открывать через ... секунд')),
                ('siteUrlBase', models.URLField(default='', verbose_name='Базовый сайт виджета')),
                ('siteUrlUp', models.URLField(default='', max_length=120, verbose_name='Сайт свайп вверх')),
                ('siteUrlDown', models.URLField(blank=True, default='', max_length=120, verbose_name='Сайт свай вниз')),
                ('siteUrlLeft', models.URLField(blank=True, default='', max_length=120, verbose_name='Сайт свайп влево')),
                ('siteUrlRight', models.URLField(blank=True, default='', max_length=120, verbose_name='Сайт свайп вправо')),
                ('keyWords', models.CharField(max_length=120, verbose_name='Текст оффера')),
                ('image', models.ImageField(blank=True, upload_to='image/banner/lead/%Y-%m', verbose_name='Картинка банера')),
                ('imageUrl', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на картинку')),
                ('dateStart', models.DateTimeField(auto_now=True, verbose_name='Дата начала')),
                ('dateStop', models.DateTimeField(default=datetime.datetime(2021, 3, 29, 19, 45, 27, 389493), verbose_name='Дата остановки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец виджета')),
            ],
            options={
                'verbose_name': 'Тестовый лид',
                'verbose_name_plural': 'Тестовые лиды',
                'ordering': ['-dateStart', 'siteUrlBase'],
            },
        ),
        migrations.CreateModel(
            name='widgetStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.IntegerField(verbose_name='Показы')),
                ('closed', models.IntegerField(verbose_name='Закрыли')),
                ('clickUP', models.IntegerField(verbose_name='Свайп вверх')),
                ('clickDown', models.IntegerField(verbose_name='Свайп вниз')),
                ('staticCreate', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('staticUpdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.testlead', verbose_name='Виджет')),
            ],
            options={
                'verbose_name': 'Статистика виджета',
                'verbose_name_plural': 'Статистика виджетов',
                'ordering': ['-widget'],
            },
        ),
    ]
