# Generated by Django 3.1.3 on 2021-03-22 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlead',
            name='dateStop',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 19, 46, 21, 635518), verbose_name='Дата остановки'),
        ),
    ]
