# Generated by Django 3.1.3 on 2021-04-05 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210403_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlead',
            name='widgetStatus',
            field=models.IntegerField(choices=[(0, 'В работе'), (1, 'Отключен'), (2, 'Ожидает опалаты')], default=0, verbose_name='Статус виджета'),
        ),
        migrations.AlterField(
            model_name='testlead',
            name='dateStop',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 18, 45, 4, 118012), verbose_name='Дата остановки'),
        ),
    ]
