# Generated by Django 3.1.3 on 2021-04-05 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210405_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testlead',
            old_name='widgetStatus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='testlead',
            name='dateStop',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 18, 51, 36, 812092), verbose_name='Дата остановки'),
        ),
    ]
