# Generated by Django 3.1.3 on 2021-04-13 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210405_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetstatistics',
            name='closed',
        ),
        migrations.AlterField(
            model_name='testlead',
            name='dateStop',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 13, 2, 28, 555710), verbose_name='Дата остановки'),
        ),
        migrations.AlterField(
            model_name='testlead',
            name='keyWords',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст оффера'),
        ),
        migrations.AlterField(
            model_name='widgetstatistics',
            name='clickDown',
            field=models.IntegerField(default=0, verbose_name='Свайп вниз'),
        ),
        migrations.AlterField(
            model_name='widgetstatistics',
            name='clickUP',
            field=models.IntegerField(default=0, verbose_name='Свайп вверх'),
        ),
        migrations.AlterField(
            model_name='widgetstatistics',
            name='show',
            field=models.IntegerField(default=0, verbose_name='Показы'),
        ),
    ]
