# Generated by Django 3.1.3 on 2021-04-13 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210413_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widgetstatistics',
            options={'verbose_name': 'Статистика виджета', 'verbose_name_plural': 'Статистика виджетов'},
        ),
        migrations.RemoveField(
            model_name='widgetstatistics',
            name='widget',
        ),
        migrations.AddField(
            model_name='testlead',
            name='statick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.widgetstatistics', verbose_name='Статистика'),
        ),
        migrations.AlterField(
            model_name='testlead',
            name='dateStop',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 17, 58, 49, 608518), verbose_name='Дата остановки'),
        ),
    ]
