# Generated by Django 3.1.3 on 2021-04-27 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210413_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlead',
            name='dateStop',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 21, 27, 16, 82988), verbose_name='Дата остановки'),
        ),
        migrations.AlterField(
            model_name='testlead',
            name='openTime',
            field=models.IntegerField(default=5, help_text='при 0 открывается сразу', verbose_name='Открывать через ... секунд'),
        ),
    ]
