# Generated by Django 3.1.3 on 2021-04-30 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210427_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlead',
            name='imageCanvaID',
            field=models.CharField(blank=True, max_length=15, verbose_name='Canva ID'),
        ),
        migrations.AlterField(
            model_name='testlead',
            name='dateStop',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 1, 32, 8, 209059), verbose_name='Дата остановки'),
        ),
        migrations.AlterField(
            model_name='testlead',
            name='title',
            field=models.CharField(default='Смахни вверх', max_length=120, verbose_name='Текст кнопки'),
        ),
    ]
